resource "tls_private_key" "deployer" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "deployer" {
  key_name   = "terraform"
  public_key = tls_private_key.deployer.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.deployer.private_key_pem
  filename        = "${path.module}/terraform.pem"
  file_permission = "0600"
}

output "local_private_key_path" {
  value       = "${path.module}/terraform.pem"
  description = "Path to the private key file generated by Terraform"
}
